"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
export default function Editor({ article }: { article?: any }) {
  const [f, setF] = useState({ titleZh: article?.titleZh || "", titleEn: article?.titleEn || "", slug: article?.slug || "", excerptZh: article?.excerptZh || "", excerptEn: article?.excerptEn || "", coverUrl: article?.coverUrl || "", contentZh: article?.contentZh || "", contentEn: article?.contentEn || "", category: article?.category || "", tags: article?.tags?.join(", ") || "", tagsEn: article?.tagsEn?.join(", ") || "", isPremium: article?.isPremium || false, status: article?.status || "DRAFT" });
  const [msg, setMsg] = useState(""); const router = useRouter();
  function update(k: string, v: any) { setF(x => ({ ...x, [k]: v })); }
  async function save(status: string) { const r = await fetch(article ? `/api/articles/${article.id}` : "/api/articles", { method: article ? "PUT" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...f, status, tags: f.tags.split(",").map((x: string) => x.trim()).filter(Boolean), tagsEn: f.tagsEn.split(",").map((x: string) => x.trim()).filter(Boolean) }) }); if (r.ok) router.push("/dashboard"); else setMsg(await r.text()); }
  return <section className="form" style={{ maxWidth: 800 }}><div className="kicker">Editor</div><h2>{article ? "Edit story" : "New story"}</h2>{msg && <div className="notice">{msg}</div>}<div className="field"><label>标题（中文）</label><input value={f.titleZh} onChange={e => update("titleZh", e.target.value)} /></div><div className="field"><label>Title (English)</label><input value={f.titleEn} onChange={e => update("titleEn", e.target.value)} /></div><div className="field"><label>Slug</label><input value={f.slug} onChange={e => update("slug", e.target.value)} /></div><div className="field"><label>摘要（中文）</label><input value={f.excerptZh} onChange={e => update("excerptZh", e.target.value)} /></div><div className="field"><label>Excerpt (English)</label><input value={f.excerptEn} onChange={e => update("excerptEn", e.target.value)} /></div><div className="field"><label>封面图 URL（可选，V1 支持外部图片/R2 URL）</label><input value={f.coverUrl} onChange={e => update("coverUrl", e.target.value)} /></div><div className="field"><label>正文（中文，支持纯文本换行）</label><textarea value={f.contentZh} onChange={e => update("contentZh", e.target.value)} /></div><div className="field"><label>Body (English)</label><textarea value={f.contentEn} onChange={e => update("contentEn", e.target.value)} /></div><div className="field"><label>分类</label><input value={f.category} onChange={e => update("category", e.target.value)} /></div><div className="field"><label>标签（中文，逗号分隔）</label><input value={f.tags} onChange={e => update("tags", e.target.value)} /></div><div className="field"><label>Tags (English, comma separated)</label><input value={f.tagsEn} onChange={e => update("tagsEn", e.target.value)} /></div><label><input style={{ width: "auto", marginRight: 8 }} type="checkbox" checked={f.isPremium} onChange={e => update("isPremium", e.target.checked)} />会员专属文章</label><div style={{ marginTop: 24 }}><button className="button alt" onClick={() => save("DRAFT")}>Save draft</button> <button className="button" onClick={() => save("PUBLISHED")}>Publish</button></div></section>;
}
